version: "3.8"

services:
  nginx-http-sever:
    container_name: "nginx-http-server"
    image: nginx:1.21-alpine
    command: ["nginx", "-g", "daemon off;"]
    restart: always
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/.tmp/static:/usr/share/nginx/html/static
    ports:
      - "80:80"
      - "443:443"
